Reject port numbers that aren't composed only of ASCII digits.
python-hyper/rfc3986 pull request #89
Opened 2022-11-12 23:02 UTC by kenballus

Parsing port numbers with `int` allows port numbers to be
 - padded with whitespace (ASCII or unicode)
 - preceded by a plus or minus sign
 - interrupted with underscores
 - composed of unicode digits

None of these behaviors are permitted by any of the URL specifications. This PR adds a check to make sure that ports get rejected if they contain any characters that aren't ASCII digits.

A [similar bug](https://github.com/python/cpython/pull/98273) was recently fixed in CPython's urllib.parse module.

2022-11-12 23:44 UTC, sethmlarson requested changes
Thank you! Can we add a test case that verifies we don't regress on this fix?

2022-11-13 00:10 UTC, kenballus commented
> Thank you! Can we add a test case that verifies we don't regress on this fix?

Done!

2022-11-13 00:30 UTC, sigmavirus24 approved these changes

2022-11-13 00:35 UTC, sethmlarson approved these changes

2022-11-13 00:35 UTC, merged